### ISSUE TITLE
Moonlight Mode added to all of my Yeelight Bulbs after updating Homebridge Plugin

### ISSUE THREAD

**Issue by Fookes74** [vieira/homebridge-yeelight-wifi#50]
Updated to 1.1.0

On all of my bulbs a new Moonlight mode has been added - Having checked it appears this should only be on ceiling lights - not standard Yeelight bulbs.  Nothing happens when toggling these new switches on/off.

**Comment by vieira** [comment]
Hello, thanks for reporting. It seems moonlight is being enabled on all devices supporting `set_scene`, which most do, even the ones not supporting moonlight. We should enable only for devices with prop `active_mode`.

**Comment by vieira** [comment]
Should be fixed in 288ec70. @Fookes74 can you confirm before I release? @okonet could you please have a look and confirm that with this change moonlight still shows on the ceiling light as intended?

Thanks!

**Comment by okonet** [comment]
LGTM let’s release and see if that still works

**Comment by Fookes74** [comment]
@vieira - excuse my ignorance. How do I test before release?

**Comment by okonet** [comment]
@Fookes74 I'm running the plugin on my local machine with a test homebridge installation. See instructions https://github.com/nfarina/homebridge#plugin-development

**Comment by vieira** [comment]
@Fookes74 @okonet I have just released a new version, 1.1.1. Can you check if that solves the issue and does not break moonlight on the ceiling light? Thanks!

**Comment by Fookes74** [comment]
Just updated, restarted, and unfortunately the additional switch is still showing on my tiles for each yeelight (all bulbs - I don’t have a ceiling light). Therefore it hasn’t resolved it for me.

**Comment by vieira** [comment]
Hello @Fookes74,

I have just tested with one of my bulbs and it seems fine now:

![Screenshot 2019-12-11 at 14 19 11](https://user-images.githubusercontent.com/207460/70629351-bedeea80-1c21-11ea-9366-f2f427e15033.jpeg)

You might need to delete `accessories/cachedAccessories` (should be near your `config.json` file) as the previous version might have caused the device to be cached with the wrong characteristics.

Let me know how it goes.

Sorry and thanks.

**Comment by Fookes74** [comment]
I take it deleting cachedAccessories will mean configuring my entire home bridge setup again?

**Comment by vieira** [comment]
Hello @Fookes74, that should not be the case, the bridge configuration and IDs should be in `persist/`.

However, if you would like to avoid any risks, you can edit the file and just remove the entries related to `homebridge-yeelight-wifi`, leaving everything else untouched. You might need to rename the yeelight bulbs again.

Let me know if there is anything else I can do to help.

**Comment by Fookes74** [comment]
Not getting this. Deleted accessories folder by issuing command: rm -rf accessories 

rebooted HOOBS and still the same issue. Am I doing something wrong?

**Comment by vieira** [comment]
@Fookes74 hmm not sure, can you share your `cachedAccessories` file and the relevant logs?

**Comment by Fookes74** [comment]
Homebridge Logs:

[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":710}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":711}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":712}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":713}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":714}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":715}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] {"method":"get_prop","params":["power"],"id":716}
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] { id: 710, result: [ 'off' ] }
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] { id: 711, result: [ 'off' ] }
[Homebridge] [12/11/2019, 20:00:46] [Yeelight] { id: 712, result: [ 'on' ] }

The names of the devices (in the logs) no longer show but they're all still showing correctly in the Home app - just with this additional toggle for each light. 

How do I share my cachedAccessories file? Sorry, I'm not great at all of this. I'm SSHing in to the Pi and I can see the file. Not sure how to share that with you.

**Comment by vieira** [comment]
Sorry, it will be easier to stop homebridge, delete the `acessories/` and `persist/` folders and start homebridge. You will probably have to remove and readd homebridge in the Home app. 😞

See [Homebridge troubleshooting](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories) for step by step instructions.

**Comment by vieira** [comment]
@Fookes74 were you able to resolve it?

**Comment by Fookes74** [comment]
I’m weighing up the risk of re-setting up my entire Homebridge and something not going back in as it should. I have Aqara Homekit Hub and it was quite flaky going in for a few attempts. Finally got it in and it’s solid now - just don’t want issues trying to re-add. 

Could have really done without this!

Chris Dafforne

**Comment by vieira** [comment]
@Fookes74, I understand. If you can share your `cachedAccessories` and files in the `persist/` folder I might be able to take a look. You can run e.g. `cat cachedAccessories | nc termbin.com 9999` and share the URL.

Please make sure to not share any files with private/confidential information! At least one of the files in the `persist/` folder will have a password. Copy that file to another location and redact the password before sharing.

I cannot guarantee that I will be able to help, but I will give it a try.

**Comment by Fookes74** [comment]
Not sure how to access these files. I can ssh in to my Homebridge without issue, I can see cachedAccessories but I can’t access it (from memory). I think I looked at that when it first went weird. If you could offer guidance then that would be great.

Chris

**Comment by spn91** [comment]
Hi @vieira , your fix removed the moonlight switch from my yeelight ceiling lights. I had to add back the check of the set_scene feature to have it working again.
I am using this one -> Yeelight JIAOYUE YLXD17YL 480. The model name of this is "ceiling3" in homebridge.

**Comment by okonet** [comment]
@spunti can you create a separate issue so I can take a look at a more reliable solution?

**Comment by spn91** [comment]
@okonet done. https://github.com/vieira/homebridge-yeelight-wifi/issues/57
